server:
  port: 8072

spring:
  application:
    name: "gatewayserver"
  #config:
    #import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/elearning/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "E-learning Gateway Server Application"
    version: "1.0.0"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8075/eureka/

logging:
  level:
    com:
      mtalaat:
        gatewayserver: DEBUG