server:
  port: 8080
spring:
  application:
    name: "courses"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/e_learning
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #config:
    #import: "optional:configserver:http://localhost:8071/"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/elearning/protocol/openid-connect/certs"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8075/eureka/

info:
  app:
    name: "courses"
    description: "E-learning Courses Application"
    version: "1.0.0"

logging:
  level:
    com:
      mtalaat:
        courses: DEBUG
