server:
  port: 8081
spring:
  application:
    name: "messages"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/e_learning
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/elearning/protocol/openid-connect/certs"
    #config:
    #import: "optional:configserver:http://localhost:8071/"
    kafka:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8075/eureka/



info:
  app:
    name: "messages"
    description: "E-learning Messages Application"
    version: "1.0.0"

logging:
  level:
    com:
      mtalaat:
        messages: DEBUG
